FROM node:dubnium-alpine

WORKDIR /usr/src/app

EXPOSE 3000

COPY ./package*.json ./

RUN npm install

#google login/logout button
RUN npm install react-google-login

#QR code reader for react
RUN npm install react-qr-reader

#QR code generator for react
RUN npm install react-qr-svg

#################
RUN npm install @material-ui/core

RUN npm install react-redux

RUN npm install prop-types
##################

COPY . .

CMD ["npm", "run", "start"]